export const AWMP_TOOL_NAME = 'AWMP'

export const AWMP_TOOL_ACTIONS = [
  'list_modes',
  'route_request',
  'create_mode',
  'lint_mode',
  'install_mode',
  'catalog_modes',
  'publish_mode',
  'export_mode_bundle',
  'install_mode_bundle',
  'read_mode_lock',
  'lock_mode',
  'verify_mode_lock',
  'generate_trust_keypair',
  'read_mode_trust',
  'sign_mode',
  'verify_mode_signature',
  'read_mode_marketplace',
  'publish_marketplace_mode',
  'revoke_marketplace_mode',
  'verify_mode_marketplace',
  'sync_mode_marketplace',
  'install_marketplace_mode',
  'read_workspace_policy',
  'set_workspace_policy',
  'check_workspace_policy',
  'eval_mode',
  'run_task_file',
  'start_task',
  'list_approvals',
  'list_artifact_reviews',
  'record_artifact_review',
  'inspect_run',
  'eval_runs',
  'approve_request',
  'reject_request',
  'call_registered_tool',
  'run_scheduler_step',
  'retry_scheduler_step',
  'run_scheduler',
] as const

export type AwmpToolAction = (typeof AWMP_TOOL_ACTIONS)[number]
